/*
 * generated by Xtext 2.9.1
 */
package ar.edu.unq.tvd.nclgenerator.validation

import ar.edu.unq.tvd.nclgenerator.nCLGenerator.Media
import ar.edu.unq.tvd.nclgenerator.nCLGenerator.NCL
import org.eclipse.xtext.validation.Check
import ar.edu.unq.tvd.nclgenerator.nCLGenerator.NCLGeneratorPackage
import ar.edu.unq.tvd.nclgenerator.nCLGenerator.Region

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class NCLGeneratorValidator extends AbstractNCLGeneratorValidator {
	
	public static val DUPLICATE_NAME = 'duplicateName'

	@Check
	def checkExtencionDemas(NCL ncl){
		if(ncl.name.contains('.ncl'))
			error("El nombre del archivo no deve llevar la extencion", null)
	}
	
	@Check
	def checkForMediasWithSameName(Media media) {
		if(media.model.medias.filter[m | m.name.toLowerCase == media.name.toLowerCase].size > 1){
			error('''Duplicate media '«media.name»' ''', media, NCLGeneratorPackage.Literals.MEDIA__NAME, DUPLICATE_NAME)
		}
	}
	
	@Check
	def checkForRegionsWithSameName(Region region) {
		if(region.model.regions.filter[r | r.name.toLowerCase == region.name.toLowerCase].size > 1){
			error('''Duplicate region '«region.name»' ''', region, NCLGeneratorPackage.Literals.REGION__NAME, DUPLICATE_NAME)
		}
	}
	

	
	// Extension methods to get the model
	def model(Media it) {eContainer as NCL}
	def model(Region it) {eContainer as NCL}
}
