/*
 * generated by Xtext 2.9.1
 */
package ar.edu.unq.tvd.nclgenerator


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NCLGeneratorStandaloneSetup extends NCLGeneratorStandaloneSetupGenerated {

	def static void doSetup() {
		new NCLGeneratorStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
